# Generated by Django 4.2.8 on 2023-12-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory1',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site1.location1'),
        ),
        migrations.AlterField(
            model_name='inventory1',
            name='modification_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory1',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.inventory1'),
        ),
        migrations.AlterField(
            model_name='productinventory1',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.product1'),
        ),
    ]
